export const INTRADAY_INTERVAL = {
  MINUTE: 'MINUTE',
  '5MINUTES': '5MINUTES',
  '30MINUTES': '30MINUTES',
  HOUR: 'HOUR',
}

export const INTERDAY_INTERVAL = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUATERLY',
  ANNUAL: 'ANNUAL',
}
